# SPDX-FileCopyrightText: 2023 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2023 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
name: "CI"

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  NANOBENCH_SUPPRESS_WARNINGS: 1
  TZ: Europe/Berlin

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-22.04, compiler: spdx_license_lint}
          - {os: ubuntu-22.04, compiler: gcc-third-latest-cpp20-release}
          - {os: ubuntu-22.04, compiler: gcc-second-latest-cpp20-release}
          - {os: ubuntu-22.04, compiler: gcc-latest-cpp20-release}
          - {os: ubuntu-22.04, compiler: gcc-latest-cpp23-release}
          - {os: ubuntu-22.04, compiler: gcc-latest-cpp26-release}
          - {os: ubuntu-22.04, compiler: gcc-latest-cpp20-debug-sanitize_address}
          - {os: ubuntu-22.04, compiler: gcc-latest-cpp20-debug-sanitize_undefined}
          - {os: ubuntu-22.04, compiler: gcc-latest-cpp20-debug-sanitize_thread}
          - {os: ubuntu-22.04, compiler: clang-second-latest-cpp20-release}
          - {os: ubuntu-22.04, compiler: clang-latest-cpp20-release}
          - {os: macos-13,     compiler: gcc-latest-cpp20-release}
          - {os: macos-13,     compiler: clang-latest-cpp20-release}
          - {os: macos-14,     compiler: gcc-latest-cpp20-release}
          - {os: macos-14,     compiler: clang-latest-cpp20-release}
          - {os: windows-2022, compiler: msvc-cpp20-release}
          - {os: windows-2022, compiler: msvc-cpp20-debug}
#          - {os: ubuntu-22.04, compiler: emscripten-cpp20-release, cmake_flags: "-DCMAKE_EXE_LINKER_FLAGS='-sALLOW_MEMORY_GROWTH=1 -sSTACK_SIZE=10000000 -sMEMORY64'", cmake_cxx_flags: "-Wno-c++11-narrowing -sMEMORY64"}
    steps:
      - name: Standard IV-project testing
        uses: iv-project/IVaction@v10.13
        with:
          compiler: ${{ matrix.compiler }}
          threads: 2
          cmake_flags: ${{ matrix.cmake_flags }}
          cmake_c_flags: ${{ matrix.cmake_c_flags }}
          cmake_cxx_flags: ${{ matrix.cmake_cxx_flags }}
  final:
    runs-on: ubuntu-22.04
    name: final-pass
    needs: build
    if: always()
    steps:
      - name: Succeeded
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: CI failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
